### PR TITLE
Additions to the DF service

### PR DESCRIPTION
**Pull request by asdaraujo**
This is the same PR as sent before but without the "hacks" in common.py.
This includes only the new additions in the DF service

### CODE REVIEW

**Review by wmudge — APPROVED** [review]

**Comment by Chaffelson** [comment]
@asdaraujo Can you please address the DCO error on this.
@wmudge I co-authored with Andre, can you or @jimright please review so we can get this in for UDD Demo automation.

**Review by jimright — APPROVED** [review]
Used the code changes in this PR as part of my testing of https://github.com/cloudera-labs/cloudera.cloud/pull/62. All worked well. Haven't tested the data visualisation additions.

FYI @asdaraujo - you are missing the sign-off message on commit [fafb30e](https://github.com/cloudera-labs/cdpy/pull/48/commits/fafb30e6cecd5cc7fe314859512e1b97c8c020a9) required for DCO.

**Comment by Chaffelson** [comment]
@wmudge 4 commits are marked as verified, but still the DCO is flagged as failed - can you see the problem?

**Review by Chaffelson — APPROVED** [review]

**Comment by jimright** [comment]
> @wmudge 4 commits are marked as verified, but still the DCO is flagged as failed - can you see the problem?

@Chaffelson, @asdaraujo  - I think the issue is that the `Signed-off-by: ...` string is missing from the commit message of https://github.com/cloudera-labs/cdpy/pull/48/commits/36425af0118e6d8a46876a261c532838199d53da. Both that string included in included in the commit message and GPG verification are needed for DCO.

**Pull request merged**
